"""Pydantic v2 Request & Response Validation DTO Schemas Package.
"""

from app.schemas.auth import (
    UserSummary,
    TokenPair,
    RegisterRequest,
    RegisterResponse,
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    LogoutResponse,
    CurrentUserResponse,
    VerifyEmailRequest,
    ResendVerificationRequest,
    VerifyEmailResponse,
    ResendVerificationResponse,
)
from app.schemas.candidate import (
    CandidateProfileCreate,
    CandidateProfileUpdate,
    CandidateProfileResponse,
    CandidateProfileDetailResponse,
    EducationCreate,
    EducationUpdate,
    EducationResponse,
    ExperienceCreate,
    ExperienceUpdate,
    ExperienceResponse,
    SkillCreate,
    SkillUpdate,
    SkillResponse,
)

__all__ = [
    "UserSummary",
    "TokenPair",
    "RegisterRequest",
    "RegisterResponse",
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "LogoutResponse",
    "CurrentUserResponse",
    "VerifyEmailRequest",
    "ResendVerificationRequest",
    "VerifyEmailResponse",
    "ResendVerificationResponse",
    "CandidateProfileCreate",
    "CandidateProfileUpdate",
    "CandidateProfileResponse",
    "CandidateProfileDetailResponse",
    "EducationCreate",
    "EducationUpdate",
    "EducationResponse",
    "ExperienceCreate",
    "ExperienceUpdate",
    "ExperienceResponse",
    "SkillCreate",
    "SkillUpdate",
    "SkillResponse",
]
