"""SQLAlchemy 2.0 ORM Entity Models Package.

IMPORTANT — Alembic Autogenerate Integration:
    Every ORM model class that inherits from Base or BaseModel MUST be imported
    in this file. Alembic's autogenerate compares Base.metadata against the live
    database schema. If a model is not imported here, its table will NOT appear
    in autogenerated migrations.

    When you create a new model, add its import below and append to __all__.
"""

# ---------------------------------------------------------------------------
# Import all ORM model classes below this line.
# Each import registers the model's table with Base.metadata.
# ---------------------------------------------------------------------------
from app.models.user import User  # noqa: F401
from app.models.refresh_token import RefreshToken  # noqa: F401

# ---------------------------------------------------------------------------
# Import domain enums for convenient re-export.
# ---------------------------------------------------------------------------
from app.models.enums import UserRole, AuthProvider  # noqa: F401

__all__: list[str] = [
    "User",
    "RefreshToken",
    "UserRole",
    "AuthProvider",
]
