"""Alembic Async Migration Environment — TalentAI API Gateway.

This is the core migration runner that Alembic executes for every command
(revision, upgrade, downgrade, stamp, etc.).

Architecture:
    - Reuses the global AsyncEngine from app.database.engine directly.
      This ensures Alembic uses the exact same connection string, SSL context,
      timeouts, and database settings as the FastAPI application.
    - Imports Base.metadata from app.database.base for schema introspection.
    - Imports all models via app.models to register them with Base.metadata
      so autogenerate can detect table additions, removals, and column changes.
    - Supports both OFFLINE (SQL script generation) and ONLINE (direct DB) modes.
    - Fully async using SQLAlchemy 2.0 run_async() pattern.
"""

import asyncio
from logging.config import fileConfig

from sqlalchemy.engine import Connection

from alembic import context

# ==============================================================================
# 1. ALEMBIC CONFIG OBJECT
# ==============================================================================
# Provides access to values within alembic.ini (e.g., script_location, loggers).
config = context.config

# ==============================================================================
# 2. LOGGING SETUP
# ==============================================================================
# Interpret the alembic.ini [loggers] section for Python logging configuration.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ==============================================================================
# 3. LOAD DATABASE URL FROM PYDANTIC SETTINGS
# ==============================================================================
# Import settings and set the URL option in Alembic config.
from app.config.settings import settings  # noqa: E402

# Enforce a minimum of 30 seconds for database connection timeout.
# Neon databases auto-suspend after 5 mins of inactivity in the free tier,
# and cold-starting can take up to 10-15 seconds.
if settings.database.connect_timeout < 30:
    settings.database.connect_timeout = 30

config.set_main_option("sqlalchemy.url", settings.database.url)

# ==============================================================================
# 4. IMPORT METADATA AND ALL MODELS
# ==============================================================================
# Base.metadata contains the schema definition for all registered ORM models.
# For autogenerate to detect schema changes, every model class must be imported
# BEFORE Alembic inspects the metadata.
from app.database.base import Base  # noqa: E402
import app.models  # noqa: E402, F401

# The MetaData object that Alembic compares against the live database schema.
target_metadata = Base.metadata

# ==============================================================================
# 5. NAMING CONVENTION FOR CONSTRAINTS
# ==============================================================================
# Explicit naming conventions ensure that autogenerated constraints have
# deterministic names across environments.
target_metadata.naming_convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — generates SQL scripts without connecting."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    """Execute migrations using the provided synchronous connection."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations in 'online' mode using the shared application engine.

    Reuses the AsyncEngine singleton from app.database.engine. This guarantees
    identical connection arguments, SSL validation context, and timeout values
    as the running FastAPI application.
    """
    from app.database.engine import engine as connectable

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    # Since Alembic runs in a short-lived CLI process, we dispose the engine
    # before exiting to close active database connections gracefully.
    await connectable.dispose()


def run_migrations_online() -> None:
    """Entry point for online migrations."""
    asyncio.run(run_async_migrations())


# ==============================================================================
# 6. MODE DISPATCH
# ==============================================================================
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
