"""Alembic Migration Revision Template — ${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

This migration was auto-generated by Alembic using the --autogenerate flag.
Review the upgrade() and downgrade() functions carefully before applying.
Always verify that downgrade() correctly reverses every change in upgrade().
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# ---------------------------------------------------------------------------
# Revision identifiers, used by Alembic to track migration graph ordering.
# ---------------------------------------------------------------------------
revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    """Apply forward schema changes.

    Contains DDL operations to move the database schema forward.
    Generated by --autogenerate or written manually.
    """
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Reverse schema changes applied by upgrade().

    Must exactly undo every operation in upgrade() to support rollback.
    """
    ${downgrades if downgrades else "pass"}
