"""Alembic Migration Revision Template — initial_empty_schema

Revision ID: 2b31940a143a
Revises: 
Create Date: 2026-08-02 20:25:52.431071+00:00

This migration was auto-generated by Alembic using the --autogenerate flag.
Review the upgrade() and downgrade() functions carefully before applying.
Always verify that downgrade() correctly reverses every change in upgrade().
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ---------------------------------------------------------------------------
# Revision identifiers, used by Alembic to track migration graph ordering.
# ---------------------------------------------------------------------------
revision: str = '2b31940a143a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward schema changes.

    Contains DDL operations to move the database schema forward.
    Generated by --autogenerate or written manually.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse schema changes applied by upgrade().

    Must exactly undo every operation in upgrade() to support rollback.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
