"""Alembic Migration Revision Template — add_minio_storage_fields

Revision ID: f989fec16afb
Revises: b2c3d4e5f6a7
Create Date: 2026-08-14 14:01:48.538556+00:00

This migration was auto-generated by Alembic using the --autogenerate flag.
Review the upgrade() and downgrade() functions carefully before applying.
Always verify that downgrade() correctly reverses every change in upgrade().
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ---------------------------------------------------------------------------
# Revision identifiers, used by Alembic to track migration graph ordering.
# ---------------------------------------------------------------------------
revision: str = 'f989fec16afb'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward schema changes.

    Contains DDL operations to move the database schema forward.
    Generated by --autogenerate or written manually.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_resumes', sa.Column('storage_provider', sa.String(length=50), server_default=sa.text("'minio'"), nullable=True))
    op.add_column('candidate_resumes', sa.Column('bucket_name', sa.String(length=255), server_default=sa.text("'talentai-resumes'"), nullable=True))
    op.add_column('candidate_resumes', sa.Column('object_key', sa.String(length=1024), nullable=True))
    op.create_unique_constraint('uq_candidate_resumes_object_key', 'candidate_resumes', ['object_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse schema changes applied by upgrade().

    Must exactly undo every operation in upgrade() to support rollback.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candidate_resumes_object_key', 'candidate_resumes', type_='unique')
    op.drop_column('candidate_resumes', 'object_key')
    op.drop_column('candidate_resumes', 'bucket_name')
    op.drop_column('candidate_resumes', 'storage_provider')
    # ### end Alembic commands ###
